//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FlightsWebServiceSoap")]
    public interface FlightsWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication2.ServiceReference1.HelloWorldResponse HelloWorld(WebApplication2.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebApplication2.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name getFlightsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFlights", ReplyAction="*")]
        WebApplication2.ServiceReference1.getFlightsResponse getFlights(WebApplication2.ServiceReference1.getFlightsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFlights", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.getFlightsResponse> getFlightsAsync(WebApplication2.ServiceReference1.getFlightsRequest request);
        
        // CODEGEN: Generating message contract since element name getAllFlightsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllFlights", ReplyAction="*")]
        WebApplication2.ServiceReference1.getAllFlightsResponse getAllFlights(WebApplication2.ServiceReference1.getAllFlightsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllFlights", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.getAllFlightsResponse> getAllFlightsAsync(WebApplication2.ServiceReference1.getAllFlightsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication2.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication2.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFlightsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFlights", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.getFlightsRequestBody Body;
        
        public getFlightsRequest() {
        }
        
        public getFlightsRequest(WebApplication2.ServiceReference1.getFlightsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getFlightsRequestBody {
        
        public getFlightsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFlightsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFlightsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.getFlightsResponseBody Body;
        
        public getFlightsResponse() {
        }
        
        public getFlightsResponse(WebApplication2.ServiceReference1.getFlightsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFlightsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication2.ServiceReference1.ArrayOfString[] getFlightsResult;
        
        public getFlightsResponseBody() {
        }
        
        public getFlightsResponseBody(WebApplication2.ServiceReference1.ArrayOfString[] getFlightsResult) {
            this.getFlightsResult = getFlightsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllFlightsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllFlights", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.getAllFlightsRequestBody Body;
        
        public getAllFlightsRequest() {
        }
        
        public getAllFlightsRequest(WebApplication2.ServiceReference1.getAllFlightsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllFlightsRequestBody {
        
        public getAllFlightsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllFlightsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllFlightsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.getAllFlightsResponseBody Body;
        
        public getAllFlightsResponse() {
        }
        
        public getAllFlightsResponse(WebApplication2.ServiceReference1.getAllFlightsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllFlightsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication2.ServiceReference1.ArrayOfString getAllFlightsResult;
        
        public getAllFlightsResponseBody() {
        }
        
        public getAllFlightsResponseBody(WebApplication2.ServiceReference1.ArrayOfString getAllFlightsResult) {
            this.getAllFlightsResult = getAllFlightsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FlightsWebServiceSoapChannel : WebApplication2.ServiceReference1.FlightsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlightsWebServiceSoapClient : System.ServiceModel.ClientBase<WebApplication2.ServiceReference1.FlightsWebServiceSoap>, WebApplication2.ServiceReference1.FlightsWebServiceSoap {
        
        public FlightsWebServiceSoapClient() {
        }
        
        public FlightsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlightsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.HelloWorldResponse WebApplication2.ServiceReference1.FlightsWebServiceSoap.HelloWorld(WebApplication2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication2.ServiceReference1.HelloWorldRequest inValue = new WebApplication2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication2.ServiceReference1.HelloWorldRequestBody();
            WebApplication2.ServiceReference1.HelloWorldResponse retVal = ((WebApplication2.ServiceReference1.FlightsWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> WebApplication2.ServiceReference1.FlightsWebServiceSoap.HelloWorldAsync(WebApplication2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebApplication2.ServiceReference1.HelloWorldRequest inValue = new WebApplication2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication2.ServiceReference1.HelloWorldRequestBody();
            return ((WebApplication2.ServiceReference1.FlightsWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.getFlightsResponse WebApplication2.ServiceReference1.FlightsWebServiceSoap.getFlights(WebApplication2.ServiceReference1.getFlightsRequest request) {
            return base.Channel.getFlights(request);
        }
        
        public WebApplication2.ServiceReference1.ArrayOfString[] getFlights() {
            WebApplication2.ServiceReference1.getFlightsRequest inValue = new WebApplication2.ServiceReference1.getFlightsRequest();
            inValue.Body = new WebApplication2.ServiceReference1.getFlightsRequestBody();
            WebApplication2.ServiceReference1.getFlightsResponse retVal = ((WebApplication2.ServiceReference1.FlightsWebServiceSoap)(this)).getFlights(inValue);
            return retVal.Body.getFlightsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.getFlightsResponse> WebApplication2.ServiceReference1.FlightsWebServiceSoap.getFlightsAsync(WebApplication2.ServiceReference1.getFlightsRequest request) {
            return base.Channel.getFlightsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.getFlightsResponse> getFlightsAsync() {
            WebApplication2.ServiceReference1.getFlightsRequest inValue = new WebApplication2.ServiceReference1.getFlightsRequest();
            inValue.Body = new WebApplication2.ServiceReference1.getFlightsRequestBody();
            return ((WebApplication2.ServiceReference1.FlightsWebServiceSoap)(this)).getFlightsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.getAllFlightsResponse WebApplication2.ServiceReference1.FlightsWebServiceSoap.getAllFlights(WebApplication2.ServiceReference1.getAllFlightsRequest request) {
            return base.Channel.getAllFlights(request);
        }
        
        public WebApplication2.ServiceReference1.ArrayOfString getAllFlights() {
            WebApplication2.ServiceReference1.getAllFlightsRequest inValue = new WebApplication2.ServiceReference1.getAllFlightsRequest();
            inValue.Body = new WebApplication2.ServiceReference1.getAllFlightsRequestBody();
            WebApplication2.ServiceReference1.getAllFlightsResponse retVal = ((WebApplication2.ServiceReference1.FlightsWebServiceSoap)(this)).getAllFlights(inValue);
            return retVal.Body.getAllFlightsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.getAllFlightsResponse> WebApplication2.ServiceReference1.FlightsWebServiceSoap.getAllFlightsAsync(WebApplication2.ServiceReference1.getAllFlightsRequest request) {
            return base.Channel.getAllFlightsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.getAllFlightsResponse> getAllFlightsAsync() {
            WebApplication2.ServiceReference1.getAllFlightsRequest inValue = new WebApplication2.ServiceReference1.getAllFlightsRequest();
            inValue.Body = new WebApplication2.ServiceReference1.getAllFlightsRequestBody();
            return ((WebApplication2.ServiceReference1.FlightsWebServiceSoap)(this)).getAllFlightsAsync(inValue);
        }
    }
}
